"""add_exchange_to_ingestion_batches

Revision ID: 3cdf0ab6e0e0
Revises: 969c4b8a1fd4
Create Date: 2026-09-27 11:29:03.454201

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "3cdf0ab6e0e0"
down_revision: str | None = "969c4b8a1fd4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("ingestion_batches", sa.Column("exchange", sa.String(length=16), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("ingestion_batches", "exchange")
    # ### end Alembic commands ###
